
# html lang
language: default

#博客内标题
blog_title: YunfeiHe's Blog

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  # Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
# - /css/test.css
- /css/bootstrap.min.css
- /css/custom.css
- /css/pace.css

# scripts loaded in the end of the body
scripts:
- /js/bootstrap.min.js
- /js/jquery-2.1.3.min.js
- /js/modernizr.custom.js
- /js/pace.min.js
- /js/script.js
